export const googleauthconstants={
    AUTHGOOGLE_REQUEST:"AUTHGOOGLE_REQUEST",
    AUTHGOOGLE_SUCCESS:"AUTHGOOGLE_SUCCESS",
    AUTHGOOGLE_FAILURE:"AUTHGOOGLE_FAILURE",

}

export const signupconstants={
    SIGNUP_REQUEST:"SIGNUP_REQUEST",
    SIGNUP_SUCCESS:"SIGNUP_SUCCESS",
    SIGNUP_FAILURE:"SIGNUP_FAILURE"

}

export const loginconstants={
    LOGIN_REQUEST:"LOGIN_REQUEST",
    LOGIN_SUCCESS:"LOGIN_SUCCESS",
    LOGIN_FAILURE:"LOGIN_FAILURE"
}