export const googleauthconstants={
    AUTHGOOGLE_REQUEST:"AUTHGOOGLE_REQUEST",
    AUTHGOOGLE_SUCCESS:"AUTHGOOGLE_SUCCESS",
    AUTHGOOGLE_FAILURE:"AUTHGOOGLE_FAILURE",

}

export const signupconstants={
    SIGNUP_REQUEST:"SIGNUP_REQUEST",
    SIGNUP_SUCCESS:"SIGNUP_SUCCESS",
    SIGNUP_FAILURE:"SIGNUP_FAILURE"

}

export const loginconstants={
    LOGIN_REQUEST:"LOGIN_REQUEST",
    LOGIN_SUCCESS:"LOGIN_SUCCESS",
    LOGIN_FAILURE:"LOGIN_FAILURE"
}

export const postsConstants={
    GET_POSTS_REQUEST : "GET_POSTS_REQUEST",
    GET_POSTS_SUCCESS: "GET_POSTS_SUCCESS",
    GET_POSTS_ERROR:"GET_POSTS_ERROR",

    ADD_POSTS_REQUEST : "ADD_POSTS_REQUEST",
    ADD_POSTS_SUCCESS: "ADD_POSTS_SUCCESS",
    ADD_POSTS_ERROR:"ADD_POSTS_ERROR",

    GET_POSTS_BY_ID_REQUEST :"GET_POSTS_BY_ID_REQUEST",
    GET_POSTS_BY_ID_SUCCESS:"GET_POSTS_BY_ID_SUCCESS",
    GET_POSTS_BY_ID_ERROR:"GET_POSTS_BY_ID_ERROR" ,

    DELETE_POSTS_BY_ID_REQUEST :" DELETE_POSTS_BY_ID_REQUEST",
    DELETE_POSTS_BY_ID_SUCCESS:" DELETE_POSTS_BY_ID_SUCCESS",
    DELETE_POSTS_BY_ID_ERROR:" DELETE_POSTS_BY_ID_ERROR"
}